[tool.poetry]
name = "useless_bot"
version = "2.0"
description = "self-hosted discord bot"
license = "MIT"
authors = ["John Toniutti <mrvillager.dev@gmail.com>"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Framework :: aiohttp",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: English",
    "Programming Language :: Python :: 3.9",
    "Topic :: Communications :: Chat",
]

[tool.poetry.scripts]
create_db = 'useless-bot.scripts.create_db:main'

[tool.poetry.dependencies]
python = "^3.9"
discord-pretty-help = "*"
aiohttp = { version = ">=3.7.4", extras = ["speedups"] }
uvloop = { version = "*", markers = "sys_platform == 'linux'" }
"discord.py" = { git = "https://github.com/MRvillager/discord.py.git", extras = ["voice"] }

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
